### ISSUE TITLE
 Package error: ‘neldermead’

### ISSUE THREAD

**Issue by MatixR** [rubensmoura87/MultiATSM#2]
Hi, Rubens,

Great work for the package. 

I have met one error that I want to show you.
          
          Package ‘neldermead’ was removed from the CRAN repository. 
                 https://cran.r-project.org/web/packages/neldermead/index.html
          Package ‘optimbase’ was removed from the CRAN repository. 
                https://cran.r-project.org/web/packages/optimsimplex/index.html
          Package ‘optimsimplex’ was removed from the CRAN repository. 
              https://cran.r-project.org/web/packages/optimsimplex/index.html

Your code does not work for  missing package(s).  It stops at at the process of optimization. 

One possible solution is to install the missing package(s) form the local disk after download them manually. 

Another way is to change other optimization function.

Hopefully, that would help you !

xuankai zhao

xuankaizhao@126.com

**Comment by rubensmoura87** [comment]
Hi ,

**Comment by rubensmoura87** [comment]
Hi Xuankai,  
Thanks for your message.
https://github.com/rubensmoura87/drat/tree/master/docs

**Comment by rubensmoura87** [comment]
Hi Xuankai,
Thanks for your message.

Indeed, the neldermead package is no longer available at CRAN. Alternatively, you may wish to install it through my personal repository so that you can perform the optimization parts of the code:
https://github.com/rubensmoura87/drat/tree/master/docs

I hope this helps to solve the issue.

Best,
Rubens
